CREATE TABLE IP2GEOLOCATION
(
  IP            VARCHAR2(40 char) NOT NULL PRIMARY KEY, 
  CREATED 	TIMESTAMP NOT NULL,
  COUNTRY_CODE  VARCHAR2(2 char) NOT NULL, 
  REGION        VARCHAR2(100 char),
  CITY          VARCHAR2(100 char),
  TIMEZONE      VARCHAR2(40 char),
  LATITUDE      NUMBER(8,5),
  LONGITUDE     NUMBER(8,5),
  ORGANISATION  VARCHAR2(100 char)
)
/